//! Public API contract for the `AuthZ` resolver.
//!
//! `AuthZResolverApi` is a transport-agnostic `#[toolkit::contract]`: the
//! same trait is used for in-process consumption (the gear registers a local
//! impl in `ClientHub`) and for out-of-process consumption (a directory-
//! resolving REST client generated by the [`rest`](crate::rest) projection).
//! Consumers depend on it via `#[toolkit::consumes(contract = ..., from =
//! "authz-resolver")]` and never branch on the binding mode.

use toolkit_canonical_errors::CanonicalError;
use toolkit_security::PlatformSecurityContext;

use crate::models::{EvaluationRequest, EvaluationResponse};

/// Public API contract for the `AuthZ` resolver gateway (PDP).
///
/// Registered in `ClientHub` as `Arc<dyn AuthZResolverApi>` and consumed by
/// gears acting as Policy Enforcement Points (usually via
/// [`PolicyEnforcer`](crate::pep::PolicyEnforcer)).
///
/// Access denial is expressed via `EvaluationResponse.decision == false`, not
/// as an error; the `CanonicalError` return covers infrastructure/transport
/// failures only.
#[toolkit::contract(gear = "authz-resolver", version = "v1")]
pub trait AuthZResolverApi: Send + Sync {
    /// Evaluate an authorization request. Safe read (no side effects).
    ///
    /// This is a **platform-plane** method (`cpt-cf-adr-two-plane-auth`): `ctx`
    /// is a compile-time plane marker, not a tenant identity. Over REST the
    /// generated client attaches the process's internal (service-identity)
    /// credential — sourced below the contract layer, never from `ctx` — so the
    /// PDP authenticates the *calling workload*. The authorization subject
    /// itself rides in `req.subject`, which the PDP trusts from the (now
    /// service-authenticated) PEP.
    ///
    /// Callers that hold no real [`PlatformSecurityContext`] (the usual case for
    /// a tenant-plane PEP) pass [`PlatformSecurityContext::outbound_marker`].
    ///
    /// # Errors
    ///
    /// Returns a `CanonicalError` on transport/infrastructure failure or when
    /// no `AuthZ` plugin is available. An allow/deny *decision* is returned as
    /// `Ok(EvaluationResponse)`.
    #[idempotency(SafeRead)]
    async fn evaluate(
        &self,
        ctx: PlatformSecurityContext,
        req: EvaluationRequest,
    ) -> Result<EvaluationResponse, CanonicalError>;
}
